### ISSUE TITLE
Make a Python wrapper for EPIC

### ISSUE THREAD

**Issue by gusennan** [donaldlab/OSPREY3#132]
Epic is implemented in Osprey but doesn't yet have a friendly Python interface.

- [ ] Add a python interface
- [ ] Add an example script using EPIC
- [ ] Add any documentation needed to help people understand how to use EPIC.
